### ISSUE TITLE
Podman in podman

### ISSUE THREAD

**Issue by pradyparanjpe** [jonasbb/podman-gitlab-runner#11]
Is there a way to set up "podman as a custom executor" in  the image docker.io/gitlab/gitlab-runner:alpine?

Something such as: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-the-docker-image-docker-in-docker

**Comment by jonasbb** [comment]
I don't understand your question.

Yes, you can run podman in podman. I am using this executor to build new images in CI. The only problem there is that nesting overlayfs doesn't work, so you might want to pass `--storage-driver=vfs` to the nested podman.

I don't see how this relates to gitlab/gitlab-runner:alpine though, since that is a way to install gitlab-runner.

**Comment by pradyparanjpe** [comment]
This should answer my question.

The Arg: ``--storage-driver=vfs`` part is what I wanted.

README.md file explains how one should use your scripts as a custom podman executor on an installed runner.

I was trying to extend it to "podman in podman" platform by extending the mentioned docker file, to install podman. But I was getting the overlayfs error as you correctly predicted. Didn't know if the reason was lack of arguments or incompatibility of alpine with docker or anything else.

I am a biologist, not a computer engineer, and just want to get this running so that I can streamline development of codes that I am writing for my research. I sincerely appologise if the resulting naivety of my question irritated you.

**Comment by jonasbb** [comment]
@pradyparanjpe Glad to hear you got it working. Your question didn't irritate me, but the brevity of it made it hard to know what you were struggling with / what you wanted to do.

I see if I can find some better documentation for podman in podman and can add it to the README.
