### ISSUE TITLE
Podman pulling image on every build despite edits to source

### ISSUE THREAD

**Issue by worthlesspenny7** [jonasbb/podman-gitlab-runner#12]
I'm trying to contribute a pull if-not-present policy for this runner similar to this [docker runner option](https://docs.gitlab.com/runner/executors/docker.html#using-the-if-not-present-pull-policy), but I can't stop podman from pulling.

In prepare.sh
```
#### Attempting to change this to enable the same as a "pull if-not-present" policy
    podman image ls   # shows that image is available
#    podman pull --authfile "$CACHE_DIR"/_authfile_"$CONTAINER_ID" "$IMAGE"
#    rm "$CACHE_DIR"/_authfile_"$CONTAI
    podman run \
        --detach \
        --name "$CONTAINER_ID" \
        --volume "$CACHE_DIR:/home/user/cache":Z \
        --pull=missing \  ## Added this line although missing is the default
        "${PODMAN_RUN_ARGS[@]}" \
        "$IMAGE"\
        sleep 999999999
```
In cleanup.sh:
```
# Try to remove all old containers, images, networks, and volumes
## this is killing the cache, need some way to maintain a cache. For now prune manually.
#podman system prune --force --volumes
```

But when I run another job, podman reaches out and pulls the container again.  What am I missing? Is this a feasible contribution?

**Comment by jonasbb** [comment]
You changed both files `prepare.sh` and `cleanup.sh` as shown in your post, but podman is pulling the image every time. Did I understand your problem correctly?

Your change looks good. You also want to copy the `--authfile "$CACHE_DIR"/_authfile_"$CONTAINER_ID"` argument to the `podman run` call though, as otherwise the authentication might be missing. A `--pull=` argument could be present in `PODMAN_RUN_ARGS`, but by default the variable is unused.

I could imagine changing the code to something like this, such that the pull policy could be overwritten in `PODMAN_RUN_ARGS`. It seems that the last specified value wins. But I am not sure if this might lead to problems when podman and rm race to access the authfile.

```bash
    podman run \
        --detach \
        --authfile "$CACHE_DIR"/_authfile_"$CONTAINER_ID" \
        --pull=always \
        --name "$CONTAINER_ID" \
        --volume "$CACHE_DIR:/home/user/cache":Z \
        "${PODMAN_RUN_ARGS[@]}" \
        "$IMAGE"\
        sleep 999999999
    rm "$CACHE_DIR"/_authfile_"$CONTAINER_ID"
```

**Comment by worthlesspenny7** [comment]
Thanks @jonasbb! Yes, you summarized my problem correctly. I'll attempt what you've suggested and get back to you next week.

**Comment by worthlesspenny7** [comment]
I wasn't able to get to this and I'm about to go on vacation. I'll close this for now and update when I can try again.
