### ISSUE TITLE
Allow overriding command

### ISSUE THREAD

**Issue by duck-rh** [jonasbb/podman-gitlab-runner#19]
Quack,

Thanks for you nice work. I'm using a custom running to run tests that require an init system. It would be handy if we could override the command in `custom_base.sh`. I could prepare a PR if you're ok with this proposal.

Regards.
\\_o<

**Comment by jonasbb** [comment]
Hi, I assume you are talking about this line:
https://github.com/jonasbb/podman-gitlab-runner/blob/3233a44f574c337447d82563bbcf7215291bd714/prepare.sh#L66

That seems fine to extend to other commands. The important part is that the container doesn't exit by itself, since the rest of the code assumes the container to run and performs `podman exec`.
The default sleep behavior should probably be kept as is, if it is not overridden in `custom_base.sh`. A PR is definitely welcome. I would appreciate it, if you could write a small example how to configure everything and place that inside `custom_base.template.sh`.

**Comment by duck-rh** [comment]
That's exactly it. Keeping the default too since there's no reason to break the current behavior and it's just fine for most use case. Will prepare a PR then :-).
